# # Basics

In [1]:
# Loading numpy
import numpy as np

In [2]:
# Creating an array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D Array
b = np.array([[1,2,3,4],[10,20,30,40]])
print(b)

[[ 1  2  3  4]
 [10 20 30 40]]


In [4]:
# Get dimensions of an array
print (a.ndim)
print (b.ndim)

1
2


In [5]:
# Get Shape
print (a.shape) 
print (b.shape) #Two rows, four columns

(3,)
(2, 4)


In [6]:
# Get type
a.dtype

dtype('int64')

In [7]:
# Can specify what type we want
a = np.array([1,2,3],dtype='int16')

In [8]:
# Get size
a.itemsize #returns number of bytes per item

2

In [9]:
# Get number of elements in the array
a.size

3

In [10]:
# Get total size of the array
print(a.size * a.itemsize)
print(a.nbytes)

6
6


# #Accessing/Changing Specific 

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r,c]
a[1,5]

13

In [13]:
# Can also use list notation to find elements
a[-1,-2]

13

In [14]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:,3]

array([ 4, 11])

In [16]:
# [start_index:end_index:step_size]
a[0,1:6:2] #first row, but start at the second element, finish at the last element and step by 2

array([2, 4, 6])

In [17]:
# Updating elements
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
# Updating multiple elements
a[:,2] = [99,99] # both sides must be the same shape
print(a)

[[ 1  2 99  4  5  6  7]
 [ 8  9 99 11 12 20 14]]


## 3-D

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
b.shape

(2, 2, 2)

In [21]:
# Get specific element (work outisde in)
b[0,1,1]

4

In [22]:
# Updating values
b[:,1,:] = [[99,88],[77,66]]
print(b)

[[[ 1  2]
  [99 88]]

 [[ 5  6]
  [77 66]]]


## Initialize Different Types of Arrays

In [23]:
# All zeroes array
np.zeros(5) # no Canadian spelling here lol

array([0., 0., 0., 0., 0.])

In [24]:
# Can specify more dimensions
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
# All 1s matrix
np.ones((3,2,2),dtype='int8')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

In [26]:
# Other number
np.full((2,2),99) #shape,value

array([[99, 99],
       [99, 99]])

In [27]:
# Any other number (full_like) -> create an array similar (like) another one you already defined
np.full_like(a,49)

array([[49, 49, 49, 49, 49, 49, 49],
       [49, 49, 49, 49, 49, 49, 49]])

In [28]:
# Random decimal numbers -> each between 0 and 1
np.random.rand(4,2)

array([[0.52401527, 0.39534935],
       [0.76309814, 0.31287044],
       [0.43520761, 0.72910562],
       [0.74089626, 0.18340467]])

In [29]:
# Random integer values
np.random.randint(7,size=(3,3))

array([[4, 1, 6],
       [1, 5, 0],
       [0, 0, 3]])

In [30]:
# Identity matrix (if you remember your linear algebra)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Repeat Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
# Copying Arrays
a = np.array([1,2,3])
b = a #this doesn't actually copy. b is a pointer here
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [33]:
# Actual copy
b = a.copy()
b[0] = 99
print(b)
print(a)

[99  2  3]
[100   2   3]


## Mathematics

In [34]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [35]:
# Basic Arithmetic
a + 2

array([3, 4, 5, 6])

In [36]:
a - 1

array([0, 1, 2, 3])

In [37]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
# Increment
a += 2
a

array([3, 4, 5, 6])

In [39]:
b = np.array([4,5,6,7])
a + b

array([ 7,  9, 11, 13])

In [40]:
# Trig
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

#### Linear Algebra

In [41]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [42]:
# Matrix Multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [43]:
# Finding determinant
np.linalg.det(np.identity(3))

1.0

#### Stats

In [44]:
# Min and Max
stats = np.array([[1,2,3],[4,5,6]])
print(np.max(stats))
print(np.min(stats))

6
1


In [45]:
# Can also do min and max on axis
np.max(stats,axis=1)

array([3, 6])

In [46]:
# Sum of all elements
np.sum(stats)

21

## Reorganizing Arrays

In [47]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

# Can reshape however you want as long as it has the same amount of values
after = before.reshape((4,2))
print(after)

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
# Horizontal stack
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Misc

#### Load Data from File

In [50]:
file = np.genfromtxt('data.txt',delimiter=",") #auto cast to float
file.astype('int16') # this makes a copy
file = file.astype('int16').copy()
file

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int16)

###### Boolean Masking and Advanced Indexing

In [51]:
file > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [52]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [53]:
file[file > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int16)

In [54]:
# Are any values greater than 50?
np.any(file > 50)

True

In [55]:
# Are any files in each column greater than 50?
np.any(file > 50,axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [56]:
((file > 50) & (file < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])